title: Baseball Elo Ratings
email: gpcdwyer@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    The site of my investigation into the statistics and sabermetrics of local baseball.

baseurl: "/baseball_elo_ratings"
url: "https://gabrieldwyer.com"

github_username:  gabrieldwyer

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compact

# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag

# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
